{
    # "110": "Reception Kitchen",
    # "107": "Meeting Pod near Triangle Table",
    # "108": "Meeting Pod 1 (on the other side of Triangle Table)",
    # "109": "Meeting Pod 2 (on the other side of Triangle Table)",
    # "129": "Printing Area near Small Kitchen",
    # "111": "Small Kitchen",
    # "71": "Workspace Area left side of WayPoint CorpLocker1",
    # "72": "Workspace Area right side of WayPoint CorpLocker1",
    # "114": "Workspace Area right side of WayPoint CorpLocker2",
    # "116": "Workspace Area in front of WayPoint CorpLocker4",
    # "126": "Workspace Area right side of WayPoint CorpLocker4",
    # "124": "Meeting Pod in front of of WayPoint CorpArcRec1",
    # "125": "Meeting Pod in front of of WayPoint CorpArcRec2",
    # "119": "Workspace Area in front of of WayPoint CorpLocker5",
    # "118": "Workspace Area right side of WayPoint CorpLocker6",
    # "62": "Workspace Area left side of WayPoint CorpLocker6",
    # "73": "Workspace Area right side of WayPoint CorpLocker8",
    # "74": "Workspace Area left side of WayPoint CorpLocker8",
    # "130": "Printing Area near WayPoint CorpActRec3",
    # "127": "Eating Area in front of WayPoint KitchenArtRec1",
    # "131": "Eating Area in front of WayPoint KitchenArtRec2",
    # "132": "Eating Area in front of WayPoint KitchenPod3",
    # "134": "Eating Area in front of Kitchen",
    # "128": "Part of the Kitchen near Bins",
    # "133": "Part of the Kitchen with Sink",
    # "137": "Workspace Area near WayPoint SuppMeetingPod1",
    # "138": "Workspace Area near WayPoint SuppLocker12",
    # "140": "Workspace Area near WayPoint SuppLocker11",
    # "136": "Meeting Pod in front of WayPoint SuppMeetingPod2",
    # "86": "Workspace Area near WayPoint SuppTransWP2",
    # "87": "Workspace Area near WayPoint SuppLocker15",
    # "135": "Printing Area near WayPoint SuppPrintCopy",
    # "146": "Workspace Area left side of WayPoint SuppLocker7",
    # "144": "Workspace Area left side of WayPoint SuppLocker8",
    # "142": "Workspace Area right side of WayPoint SuppLocker8",
    "110": "Kitchen",
    "107": "Hospitality",
    "108": "Hospitality",
    "109": "Hospitality",
    "129": "Printing Area",
    "111": "Kitchen",
    "71": "Corperative Services",
    "72": "Corperative Services",
    "114": "Corperative Services",
    "116": "Corperative Services",
    "126": "Corperative Services",
    "124": "Corperative Services",
    "125": "Corperative Services",
    "119": "Corperative Services",
    "118": "Corperative Services",
    "62": "Corperative Services",
    "73": "Corperative Services",
    "74": "Corperative Services",
    "130": "Printing Area",
    "127": "Eating Area",
    "131": "Eating Area",
    "132": "Eating Area",
    "134": "Eating Area",
    "128": "Kitchen",
    "133": "Kitchen",
    "137": "Supportive Services",
    "138": "Supportive Services",
    "140": "Supportive Services",
    "136": "Supportive Services",
    "86": "Supportive Services",
    "87": "Supportive Services",
    "135": "Supportive Services",
    "146": "Supportive Services",
    "144": "Supportive Services",
    "142": "Supportive Services",
}
